### ISSUE TITLE
On adding shard, a name mismatch error is encountered

### ISSUE THREAD

**Issue by balakhorvathnorbert** [makisu/carbon_postmark_adapter#5]
When adding the carbon_postmark_adapter dependency to shard.yml, the following error is encountered:

`Error shard name (carbon_mailgun_adapter) doesn't match dependency name (carbon_postmark_adapter)`

No other Carbon adapters produce this error.

**Comment by xaviablaza** [comment]
Are you using two adapters? @balakhorvathnorbert  `carbon_mailgun_adapter` is not referenced anywhere in the code as of this commit: 41597d0c0c3275d9778bf5bc2edc96ae70da6bed
